include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

linter:
  rules:
    prefer_single_quotes: false
    prefer_double_quotes: true
    always_specify_types: true
    prefer_final_parameters: false
    public_member_api_docs: true
    avoid_annotating_with_dynamic: true
    use_late_for_private_fields_and_variables: true
    avoid_positional_boolean_parameters: true
    prefer_final_locals: false
    unnecessary_lambdas: true
